"""Added category column in destinations table

Revision ID: 507733729f23
Revises: f031f71845f4
Create Date: 2023-06-06 10:48:06.374127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '507733729f23'
down_revision = 'f031f71845f4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('destinations', sa.Column('category', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('destinations', 'category')
    # ### end Alembic commands ###
